[storage]
library_root = "/run/media/lewelove/1000xhome/backup-everything/FB2K/Library Historyfied!/"
library_export = "~/dev/vellum-test-library/metadata_output"
environment = "~/.secrets/vellum.env"


[theme]
thumbnail_size = 190


[theme.shader]
order = "original"
path = "shaders/mountain_eq.frag"
speed = 0.5
zoom = 0.4
blur = 0.6
grain = 0.2

# path = "shaders/simplex.frag"
# speed = 0.005
# zoom = 0.8
# blur = 0.00


[manifest]
supported_extensions = [ ".flac" ]


[compiler]
unix_added = [ "unix_added_youtube", "unix_added_applemusic", "unix_added_foobar" ]
date_added = "%B %d %Y"
manifests = [ "mbid.toml", "cover_palette.toml" ]
file_subset_match = [
  "ALBUM", "ALBUMARTIST", "DATE", "GENRE",
  "COMMENT", "TITLE", "ARTIST", "TRACKNUMBER"
]


[compiler.cover_palette]
# type = "kmeansnh"
# sort = "gradient"
# args = "k=18,n=6,h=5"
type = "kmeansnv"
# sort = "original"
# threshold = 0.02
args = "k=24,n=12,d=0.0"


[manifest.keys]
albumartist = { level = "album", newline = true }
album = { level = "album" }
date = { level = "album" }

genre = { level = "album", type = "list", newline = true }
styles = { level = "album", type = "list" }

original_yyyy_mm = { level = "album", newline = true }

country = { level = "album", newline = true }
label = { level = "album" }
catalognumber = { level = "album" }
release_yyyy_mm = { level = "album" }

discogs_url = { level = "album", newline = true }
musicbrainz_url = { level = "album" }
ctdbid_url = { level = "album" }

tracknumber = { level = "track" }
title = { level = "track" }


[compiler.keys]
albumartists = { level = "album", type = "list" }
styles = { level = "album", type = "list" }
country = { level = "album" }
label = { level = "album" }
catalognumber = { level = "album" }
media = { level = "album" }
discogs_url = { level = "album" }
musicbrainz_url = { level = "album" }
ctdbid_url = { level = "album" }
unix_added_foobar = { level = "album", type = "integer" }
unix_added_applemusic = { level = "album", type = "integer" }
unix_added_youtube = { level = "album", type = "integer" }
custom_id = { level = "album" }
custom_albumartist = { level = "album", args = "custom_albumartist,artistartist,albumartist" }
custom_string = { level = "album" }
old_comment = { level = "album" }
collection = { level = "album", type = "list" }
shelves = { level = "album", type = "list" }
my_year = { level = "album", type = "list" }
replaygain_album_gain = { level = "album" }
replaygain_album_peak = { level = "album" }
musicbrainz_albumid = { level = "album" }
musicbrainz_albumartistid = { level = "album" }
musicbrainz_releasegroupid = { level = "album" }

lyrics = { level = "tracks" }
accuripid = { level = "tracks" }
ctdbid = { level = "tracks" }
discid = { level = "tracks" }
instrumental = { level = "tracks", type = "bool" }
replaygain_track_gain = { level = "tracks" }
replaygain_track_peak = { level = "tracks" }
musicbrainz_trackid = { level = "tracks" }
musicbrainz_releasetrackid = { level = "tracks" }
musicbrainz_artistid = { level = "tracks" }

cover_chroma = { level = "album", class = "function" }
cover_entropy = { level = "album", class = "function" }
# cover_palette = { level = "album", class = "function", args = "k=12,noise=0.0,conv=0.05,filter=0.002,bias=0.0" }
# cover_palette = { level = "album", class = "function", args = "type=kmeans,sort=C,k=8" }
# cover_palette = { level = "album", class = "function", args = "type=kmeans,sort=gradient,k=8,Hb=35,Ht=108,Cb=12,Ct=60,Tb=0,Tt=50" }
# cover_palette = { level = "album", class = "function", args = "type=msc,k=16,bw=0.08,mt=0.05,cg=3.0,t=0.002" }
# cover_palette = { level = "album", class = "function", args = "type=mmcq,k=8,sort=C" }
# cover_palette = { level = "album", class = "function", args = "type=auto,theme=basic,t=0.0,k=12" }
# cover_palette = { level = "album", class = "function", args = "type=msc,bw=6" }
