[storage]
library_root = "/run/media/lewelove/1000xhome/backup-everything/FB2K/Library Historyfied!/"
library_export = "~/dev/vellum-test-library/metadata_output"
thumbnail_cache_folder = "~/.vellum/thumbnails"
environment = "~/.secrets/vellum.env"

[run]
# get-lyrics = "python/loose_scripts/fetch_lyrics.py"

[theme]
thumbnail_size = 190

[theme.shader]

order = "original"

# equalize = 0.0
# equalize = 0.7
equalize = 2.0
grain = 0.02
zoom = 0.3

path = "shaders/mountain_eq.frag"
speed = 0.006
blur = 0.7

# path = "shaders/simplex.frag"
# speed = 0.005
# zoom = 0.8
# blur = 0.00

[manifest]
supported_extensions = [ ".flac" ]

[manifest.keys]
album = { level = "album" }
albumartist = { level = "album" }
date = { level = "album" }
genre = { level = "album", add_newline = true, type = "list" }
comment = { level = "album", add_newline = true }
country = { level = "album" }
label = { level = "album" }
catalognumber = { level = "album" }
media = { level = "album", add_newline = true }
discogs_url = { level = "album" }
musicbrainz_url = { level = "album", add_newline = true }
tracknumber = { level = "track" }
title = { level = "track" }
artist = { level = "track" }

[compiler]
scan_depth = 4

[compiler.keys]
country = { level = "album" }
label = { level = "album" }
catalognumber = { level = "album" }
media = { level = "album" }
discogs_url = { level = "album" }
musicbrainz_url = { level = "album" }
unix_added_local = { level = "album" }
unix_added_foobar = { level = "album" }
unix_added_applemusic = { level = "album" }
unix_added_youtube = { level = "album" }
unix_added_primary = { level = "album" }
custom_id = { level = "album" }
custom_albumartist = { level = "album", args = "custom_albumartist,artistartist,albumartist" }
custom_string = { level = "album" }
old_comment = { level = "album" }
collection = { level = "album", type = "array" }
replaygain_album_gain = { level = "album" }
replaygain_album_peak = { level = "album" }
musicbrainz_albumid = { level = "album" }
musicbrainz_albumartistid = { level = "album" }
musicbrainz_releasegroupid = { level = "album" }

lyrics = { level = "tracks" }
accuripid = { level = "tracks" }
ctdbid = { level = "tracks" }
discid = { level = "tracks" }
instrumental = { level = "tracks", type = "bool" }
replaygain_track_gain = { level = "tracks" }
replaygain_track_peak = { level = "tracks" }
musicbrainz_trackid = { level = "tracks" }
musicbrainz_releasetrackid = { level = "tracks" }
musicbrainz_artistid = { level = "tracks" }

unix_added = { level = "album", class = "function", args = "unix_added_primary,unixtimeyoutube,unixtimeapple,unixtimefoobar,unix_added_youtube,unix_added_applemusic,unix_added_foobar,unix_added_local" }
cover_chroma = { level = "album", class = "function", sync = false }
cover_entropy = { level = "album", class = "function", sync = false }
# cover_palette = { level = "album", class = "function", args = "k=12,noise=0.0,conv=0.05,filter=0.002,bias=0.0", sync = false }
# cover_palette = { level = "album", class = "function", args = "type=kmeans,sort=C,k=8", sync = false }
# cover_palette = { level = "album", class = "function", args = "type=kmeans_filtered,sort=C,k=12,mode=cut,Hb=35,Ht=108,Cb=12,Ct=60,Tb=0,Tt=50", sync = false }
# cover_palette = { level = "album", class = "function", args = "type=msc,k=16,bw=0.08,mt=0.05,cg=3.0,t=0.002", sync = false }
# cover_palette = { level = "album", class = "function", args = "type=mmcq,k=8,sort=C", sync = false }
# cover_palette = { level = "album", class = "function", args = "type=auto,theme=basic,t=0.0,k=12", sync = false }
# cover_palette = { level = "album", class = "function", args = "type=msc,bw=6", sync = false }
cover_palette = { level = "album", class = "function", args = "type=mcu_material,sort=gradient,k=12", sync = false }
