# -- GROUPERS --

[groupers.genre]
label = "Genre"
select = "${album.GENRE}"

[groupers.artists]
label = "Artists"
select = "COALESCE(NULLIF(${album.tags.ALBUMARTISTS}, {[]}), ${album.ALBUMARTIST})"
index = true

[groupers.decade]
label = "Decade"
select = "substr(${album.DATE}, 1, 3) || {0s}"

[groupers.total_tracks]
label = "Total Tracks"
select = "CAST(${album.info.total_tracks} AS TEXT)"

[groupers.total_discs]
label = "Total Discs"
select = "CAST(COALESCE(${album.info.total_discs}, 1) AS TEXT)"

[groupers.year_added]
label = "Year Added"
select = "strftime({%Y}, datetime(${album.info.unix_added}, {unixepoch}))"

[groupers.chroma]
label = "Chroma"
select = "CASE WHEN CAST(${album.tags.COVER_CHROMA} AS FLOAT) = 0 THEN {Monochrome} WHEN CAST(${album.tags.COVER_CHROMA} AS FLOAT) < 15 THEN {Bleak} WHEN CAST(${album.tags.COVER_CHROMA} AS FLOAT) < 33 THEN {Muted} WHEN CAST(${album.tags.COVER_CHROMA} AS FLOAT) < 60 THEN {Standard} ELSE {Vibrant} END"

# -- SORTERS --

[sorters.default]
label = "Default"
order_by = "CASE WHEN LOWER(COALESCE(${album.tags.CUSTOM_ALBUMARTIST}, ${album.ALBUMARTIST})) LIKE {the %} THEN SUBSTR(COALESCE(${album.tags.CUSTOM_ALBUMARTIST}, ${album.ALBUMARTIST}), 5) ELSE COALESCE(${album.tags.CUSTOM_ALBUMARTIST}, ${album.ALBUMARTIST}) END ASC, ${album.DATE} ASC, ${album.ALBUM} ASC"

[sorters.az]
label = "Alphabetical"
order_by = "${album.ALBUM} ASC"

[sorters.year]
label = "Year"
order_by = "${album.DATE} DESC"

[sorters.duration]
label = "Duration"
order_by = "CAST(${album.info.album_duration} AS INT) DESC"

[sorters.chroma]
label = "Chroma"
order_by = "CAST(${album.tags.COVER_CHROMA} AS FLOAT) DESC"

[sorters.entropy]
label = "Entropy"
order_by = "CAST(${album.tags.COVER_ENTROPY} AS INT) DESC"

[sorters.date_added]
label = "Date Added"
order_by = "COALESCE(CAST(${album.tags.UNIX_ADDED_YOUTUBE} AS INT), CAST(${album.tags.UNIX_ADDED_APPLEMUSIC} AS INT), CAST(${album.tags.UNIX_ADDED_FOOBAR} AS INT), CAST(${album.info.unix_added} AS INT)) DESC"

[sorters.last_edited]
label = "Last Edited"
order_by = "COALESCE(${album.info.metadata_toml_mtime}, 0) DESC"

# -- COLLECTIONS --

# [collections.library]
# label = "Entire Library"
# filter = "1=1"

[collections.album_library]
label = "Main Library"
filter = "COALESCE(${album.tags.COLLECTION}, '') NOT LIKE %{Vapor Memory} AND ${album.GENRE} NOT LIKE %{Signalwave} AND ${album.GENRE} NOT LIKE %{Vaporwave}"

[collections.vapor_memory]
label = "Vapor Memory"
filter = "COALESCE(${album.tags.COLLECTION}, '') LIKE %{Vapor Memory} OR ${album.GENRE} LIKE %{Vaporwave}"

[collections.signalwave]
label = "Signal Memory"
filter = "COALESCE(${album.GENRE}, '') LIKE %{Signalwave}"

# Apple Music Collection

[collections.apple_music]
label = "Apple Music"
filter = "${album.tags.UNIX_ADDED_APPLEMUSIC} IS NOT NULL"
strict = true
groupers = ["year_added_applemusic", "genre", "decade"]
sorters = ["unix_added_applemusic", "default", "az", "year"]

[groupers.year_added_applemusic]
label = "Year Added"
select = "strftime({%Y}, datetime(${album.tags.UNIX_ADDED_APPLEMUSIC}, {unixepoch}))"
strict = true

[sorters.unix_added_applemusic]
label = "Date Added"
order_by = "CAST(${album.tags.UNIX_ADDED_APPLEMUSIC} AS INT) DESC"
strict = true

# Foobar2000 Collection

[collections.foobar]
label = "Foobar2000"
filter = "${album.tags.UNIX_ADDED_FOOBAR} IS NOT NULL"
strict = true
groupers = ["year_added_foobar"]
sorters = ["unix_added_foobar"]

[groupers.year_added_foobar]
label = "Year Added"
select = "strftime({%Y}, datetime(${album.tags.UNIX_ADDED_FOOBAR}, {unixepoch}))"
strict = true

[sorters.unix_added_foobar]
label = "Date Added"
order_by = "CAST(${album.tags.UNIX_ADDED_FOOBAR} AS INT) DESC"
strict = true

# My Year

[collections.my_year]
label = "My Year"
filter = "${album.tags.MY_YEAR} IS NOT NULL"
strict = true
groupers = ["my_year_grouper"]
sorters = ["default", "date_added"]

[groupers.my_year_grouper]
label = "Year"
select = "${album.tags.MY_YEAR}"
strict = true

# -- SHELVES --

[shelves.ambient50]
label = "Ambient 50"
file = "/home/lewelove/nix-hosts/dotfiles/.config/vellum/shelves/Ambient50.txt"

