{
  description = "Vellum Core Toolchain";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }: let
    system = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.${system};
  in {
    lib = {
      mkAlbum = { pname, src, metadata ? "", ops ? "cp -r ./* $out/" }:
        let
          rawPath = if builtins.isString src && builtins.substring 0 1 src == "/"
                    then /. + src
                    else src;
          
          safeSrc = builtins.path {
            name = pname;
            path = rawPath;
          };
        in
        pkgs.stdenv.mkDerivation {
          name = pname;
          src = safeSrc;

          inherit metadata;

          buildInputs =[ pkgs.flac pkgs.shntool pkgs.ffmpeg ];
          
          passAsFile = [ "metadata" ];
          
          buildPhase = ''
            mkdir -p $out
            
            # Execute user-defined operations
            ${ops}
            
            # Copy the metadata file generated by passAsFile to the output
            cp "$metadataPath" "$out/metadata.toml"
          '';

          installPhase = "true";
        };
    };
  };
}
