add_newline = false

# We use ${custom.machine_icon} to pull in the emoji and $git_branch for the repo status.
format = """
[\\[](bright-black)[$time](bright-black)[\\]](bright-black) ${custom.machine_icon} [$username](yellow)[@](green)[$hostname](blue) [$directory](purple) $git_branch
$character
"""

[time]
disabled = false
format = "$time"
time_format = "%H:%M"

[username]
show_always = true
format = "$user"

[hostname]
ssh_only = false
format = "$hostname"
style = "blue"

[directory]
format = "$path"
truncation_length = 100
truncate_to_repo = false
style = "cyan"

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
style = "bright-black"

[character]
success_symbol = "[\\[](bright-black)[>](bright-black)[\\]](bright-black)"
error_symbol = "[\\[](bright-black)[>](bright-black)[\\]](bright-black)"

[custom.machine_icon]
when = "true"
format = "$output"
command = "uname -n | grep -iq 'home' && echo '🏠' || echo '🧪'"
